[phases.setup]
nixPkgs = ["python310", "pip"]

[phases.install]
cmds = ["pip install --upgrade pip", "pip install -r requirements.txt"]

[start]
cmd = "streamlit run Home.py --server.port=$PORT --server.address=0.0.0.0 --server.headless=true"
